const CURRENCIES=['USD','TWD','EUR','JPY','HKD'];
function normalizedExpenses(data){
 if(data.expenses===undefined)return [];
 if(!Array.isArray(data.expenses)||data.expenses.length>5000)throw Error('Invalid expenses');
 const ids=new Set();
 return data.expenses.map(e=>{if(!e||typeof e.id!=='string'||ids.has(e.id)||!Number.isSafeInteger(e.cents)||e.cents<=0||e.cents>99999999999||!CURRENCIES.includes(e.currency)||!['card','cash'].includes(e.method)||typeof e.item!=='string'||!e.item.trim()||e.item.length>200||typeof e.note!=='string'||e.note.length>2000||!/^\d{4}-\d{2}-\d{2}$/.test(e.date))throw Error('Invalid expense');ids.add(e.id);return {id:e.id,cents:e.cents,currency:e.currency,method:e.method,item:e.item,note:e.note,date:e.date}});
}
let expenseEdit=null;
function money(cents){return (cents/100).toLocaleString('zh-TW',{minimumFractionDigits:2,maximumFractionDigits:2})}
function expenses(){
 const entries=state.expenses||[],current=entries.find(x=>x.id===expenseEdit);
 const totals=CURRENCIES.map(currency=>{const rows=entries.filter(x=>x.currency===currency);return rows.length?`<div class="expense-total"><strong>${currency} ${money(rows.reduce((s,x)=>s+x.cents,0))}</strong><small>刷卡 ${money(rows.filter(x=>x.method==='card').reduce((s,x)=>s+x.cents,0))} ／ 現金 ${money(rows.filter(x=>x.method==='cash').reduce((s,x)=>s+x.cents,0))}</small></div>`:''}).join('');
 const now=new Date(),date=current?.date||[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');
 main.innerHTML=`<div class="dayhead"><h2>旅途記帳</h2><button class="btn" data-tab="報帳">報帳規則</button></div><p class="muted">隨手記下一筆花費，收據另外留好。</p>${totals?`<section class="totals">${totals}<p>依原幣別分開加總，未換算匯率。</p></section>`:''}<form id="expenseform" class="panel"><h3>${current?'編輯支出':'記一筆'}</h3><div class="form-pair"><label class="field">金額<input name="amount" type="number" inputmode="decimal" min="0.01" max="999999999.99" step="0.01" required placeholder="0.00" value="${current?current.cents/100:''}"></label><label class="field">幣別<select name="currency">${CURRENCIES.map(c=>`<option ${c===(current?.currency||'USD')?'selected':''}>${c}</option>`).join('')}</select></label></div><label class="field">項目<input name="item" required maxlength="200" placeholder="例如：午餐、計程車" value="${esc(current?.item||'')}"></label><fieldset class="payment"><legend>付款方式</legend><label><input type="radio" name="method" value="card" ${current?.method!=='cash'?'checked':''}> 刷卡</label><label><input type="radio" name="method" value="cash" ${current?.method==='cash'?'checked':''}> 現金</label></fieldset><label class="field">日期<input name="date" type="date" required value="${esc(date)}"></label><label class="field">備註（選填）<input name="memo" maxlength="2000" placeholder="店家、同行人或其他補充" value="${esc(current?.note||'')}"></label><div class="actions"><button class="btn primary" type="submit">${current?'儲存支出修改':'儲存支出'}</button>${current?'<button class="btn" type="button" data-expense-cancel>取消</button>':''}</div></form><h3>支出紀錄 <small>${entries.length} 筆</small></h3><div class="expense-list">${entries.length?[...entries].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<article class="expense-entry"><div class="notehead"><h3>${esc(x.item)}</h3><strong>${x.currency} ${money(x.cents)}</strong></div><small>${esc(x.date)} ／ ${x.method==='card'?'刷卡':'現金'}</small>${x.note?`<p class="note-text">${esc(x.note)}</p>`:''}<div class="actions"><button class="btn" data-expense-edit="${esc(x.id)}" aria-label="編輯支出 ${esc(x.item)}">編輯</button><button class="btn danger" data-expense-delete="${esc(x.id)}" aria-label="刪除支出 ${esc(x.item)}">刪除</button></div></article>`).join(''):'<p class="empty">還沒有支出，從第一筆開始記。</p>'}</div><p class="muted">支出儲存在這個裝置；到「更多 → 備忘與備份」匯出備份。</p>`;
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-expense-edit')){expenseEdit=b.dataset.expenseEdit;expenses();window.scrollTo(0,0)}if(b.hasAttribute('data-expense-cancel')){expenseEdit=null;expenses()}if(b.hasAttribute('data-expense-delete')&&await appConfirm('刪除這筆支出？')){const next=(state.expenses||[]).filter(x=>x.id!==b.dataset.expenseDelete);const old=state.expenses;state.expenses=next;if(!save()){state.expenses=old;return}expenseEdit=null;expenses();toast('支出已刪除')}});
document.addEventListener('submit',e=>{if(e.target.id!=='expenseform')return;e.preventDefault();const f=new FormData(e.target),amount=Number(f.get('amount'));const entry={id:expenseEdit||crypto.randomUUID(),cents:Math.round(amount*100),currency:f.get('currency'),item:f.get('item').trim(),method:f.get('method'),date:f.get('date'),note:f.get('memo').trim()};try{normalizedExpenses({expenses:[entry]})}catch{toast('請填寫有效的金額、項目與日期');return}const old=state.expenses||[];if(!expenseEdit&&old.length>=5000){toast('最多 5,000 筆，請先匯出備份');return}state.expenses=expenseEdit?old.map(x=>x.id===expenseEdit?entry:x):[entry,...old];if(!save()){state.expenses=old;return}expenseEdit=null;expenses();toast('支出已儲存')});
